### ISSUE TITLE
Error in metrics hourUtil and dateUtil

### ISSUE THREAD

**Issue by JuBrac** [danymat/INSAnonym-utils#56]
I have created a dataset with some lines removed with 'DEL', using existing algorithms (delete_ids) and also custom algorithms.
After i want to test metrics. I have some errors in hourUtil and dateUtil.

Here are the errors messages.
For hourUtil : 

Traceback (most recent call last):
    File "metrics\runner.py", line 51, in <module>
      score = hourUtil.main(df_anon, df_origin, {}, size_df)
    File "metrics\hourUtil.py", line 27, in main
      df['score'] = df['diff_hour'].apply(lambda x: hourdec[x])
    File "Python39\lib\site-packages\pandas\core\series.py", line 4138, in apply
      mapped = lib.map_infer(values, f, convert=convert_dtype)
    File "pandas\_libs\lib.pyx", line 2467, in pandas._libs.lib.map_infer
    File "metrics\hourUtil.py", line 27, in <lambda>
      df['score'] = df['diff_hour'].apply(lambda x: hourdec[x])
  TypeError: list indices must be integers or slices, not float

For dateUtil : 
Traceback (most recent call last):
  File "\metrics\runner.py", line 49, in <module>
    score = dateUtil.main(df_anon, df_origin, {}, size_df)
  File "\metrics\dateUtil.py", line 14, in main
    if not pd.Series(df_week == df_original_week).all():
  File "\Python39\lib\site-packages\pandas\core\ops\common.py", line 65, in new_method
    return method(self, other)
  File "\Python39\lib\site-packages\pandas\core\arraylike.py", line 29, in __eq__
    return self._cmp_method(other, operator.eq)
  File "Python39\lib\site-packages\pandas\core\series.py", line 4973, in _cmp_method
    raise ValueError("Can only compare identically-labeled Series objects")
ValueError: Can only compare identically-labeled Series objects

Thanks.

**Comment by danymat** [comment]
Hello, can you try this fix?
`git checkout fix-dtypes`

**Comment by JuBrac** [comment]
It works well now.
Thanks !

**Comment by danymat** [comment]
@JuBrac i will let you know when the patch is up and running on the website. ATM, please do your tests in local to be sure everything works.
Thanks you for your responsiveness !
